version: 2
updates:
  - package-ecosystem: npm
    directory: /config-ui
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /browser-runner
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /etl
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /config-ui
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
